name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            binPath: dist\qml-parser.exe
          # - os: ubuntu-20.04
          #   platform: linux
          #   binPath: dist/qml-parser
          # - os: macos-13
          #   platform: darwin
          #   binPath: dist/qml-parser.app/Contents/MacOS/qml-parser
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-node@v2

      - name: Build app
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ./.github/actions/winbuild

      # - name: Build app for other platforms
      #   if: ${{ matrix.os != 'windows-latest' }}
      #   uses: ./.github/actions/build
      #   with:
      #     with-package: false


      - run: npm install
      - run: npm test
